# 用于生成分别适用于客户端和服务端SSR的路由列表
# path React-router 对应的path
# module 要加载的入口模块
# chunk 模块chunk别名, 影响生成的chunk文件名
# exact React-router 对应的exact, 严格匹配路由

- path: /
  module: entries/home
  chunk: home
  exact: true
- path: /blog
  module: entries/blog
  chunk: blog
  exact: true
- path: /channels
  module: entries/channels
  chunk: channels
  exact: true
- path: /channel/:slug
  module: entries/channel
  chunk: home
  exact: false
- path: /topic/:id
  module: entries/topic
  chunk: topic
  exact: false
- path: /article/:id
  module: entries/article
  chunk: article
  exact: false
- path: /u/:username
  module: entries/uc
  chunk: uc
  exact: true
- path: /u/:username/:tab
  module: entries/uc
  chunk: uc
  exact: false
- path: /creation
  module: entries/creation
  chunk: creation
- path: /activation
  module: entries/activation
  chunk: activation
  exact: false
- path: /notification
  module: entries/notification
  chunk: notification
  exact: true
- path: /notification/page/:page
  module: entries/notification
  chunk: notification
  exact: false
- path: /notification/system
  module: entries/sysNotification
  chunk: notification
  exact: true
- path: /notification/system/page/:page
  module: entries/sysNotification
  chunk: notification
  exact: false
- path: /following
  module: entries/following
  chunk: home
  exact: true
- path: /following/users
  module: entries/followUsers
  chunk: follow
  exact: true
- path: /following/users/page:page
  module: entries/followUsers
  chunk: follow
  exact: false
- path: /following/activities
  module: entries/followActivities
  chunk: follow
  exact: true
- path: /following/activities/page/:page
  module: entries/followActivities
  chunk: follow
  exact: false
- path: /balance
  module: entries/balance
  chunk: balance
  exact: true
- path: /balance/page/:page
  module: entries/balance
  chunk: balance
  exact: false
- path: /balance/rank
  module: entries/balanceRank
  chunk: balance
  exact: true
- path: /balance/rank/page/:page
  module: entries/balanceRank
  chunk: balance
  exact: false
- path: /balance/costrank
  module: entries/balanceCostRank
  chunk: balance
  exact: true
- path: /balance/costrank/page/:page
  module: entries/balanceCostRank
  chunk: balance
  exact: false
- path:
  module: entries/notFound
  chunk: notFound
  exact: false
