# 用于生成分别适用于客户端和服务端SSR的路由列表
# path React-router 对应的path
# module 要加载的入口模块
# chunk 模块chunk别名, 影响生成的chunk文件名
# exact React-router 对应的exact, 严格匹配路由

- path: /
  module: views/home
  chunk: home
  exact: true
- path: /a
  module: views/a
  chunk: a
  exact: false
- path: /b
  module: views/b
  chunk: b
  exact: false
