# 用于生成分别适用于客户端和服务端SSR的路由列表
# path React-router 对应的path
# module 要加载的入口模块
# chunk 模块chunk别名, 影响生成的chunk文件名
# exact React-router 对应的exact, 严格匹配路由

- path: /
  module: entries/home
  chunk: home
  exact: true
- path: /blog
  module: entries/blog
  chunk: blog
  exact: true
- path: /channels
  module: entries/channels
  chunk: channels
  exact: true
- path: /channel/:id
  module: entries/channel
  chunk: channel
  exact: false
- path: /topic/:id
  module: entries/topic
  chunk: topic
  exact: false
- path: /article/:id
  module: entries/article
  chunk: article
  exact: false
- path: /u/:username
  module: entries/uc
  chunk: uc
  exact: false
- path:
  module: entries/notFound
  chunk: notFound
  exact: false
